### ISSUE TITLE
HUBOT_BANGBANG_ROLE

### ISSUE THREAD

**Issue by hanselke** [lukaspustina/hubot-bangbang#10]
How do i assign my user the HUBOT_BANGBANG_ROLE?

tried to use hubot-auth, but it seems like they have a bug that makes HUBOT_ADMIN_ROLE env var not work. at least it doesnt work with the hubot-telegram connector im using.

Are we able to somehow pass in a userid for it to have hubot_bangbang_role?

**Comment by lukaspustina** [comment]
We've pinned hubot-auth to version 1.3.0 because there are some incompatibilities especially regarding hubot-slack. With this version, authorization works fine. Please see hubot-auth version 1.3.0 for details.

I don't see sensible way to pass userids, because hubot runs as one specific Unix user.
