### ISSUE TITLE
Replace customMessage

### ISSUE THREAD

**Issue by opvizordz** [lukaspustina/hubot-bangbang#6]
robot.adapter.customMessage has been removed.
ERROR TypeError: robot.adapter.customMessage is not a function

I found the following thread: https://github.com/slackapi/hubot-slack/issues/342

**Comment by lukaspustina** [comment]
Yes, I’m aware of this issue. Unfortunately, the major version 4 of hubot-slack has been nothing more than a huge disappointment so far. It’s error prone, breaks compatibility in so many places, and — this is the worst — does not reproduce the functionality of the major version 3. For example, user management is completely unreliable. For this reasons, I decided to stick with a dependency for hubot-slack 3.x until this mess gets sorted out. To be fair, I haven’t checked 4.x for some time now.

So, if you want to use bang-bang you currently have to stick to hubot-slack 3.x. Please see https://github.com/Rheinwerk/docker-image-hubot for a dockerized example.
