### ISSUE TITLE
 ERROR hubot-bangbang: Failed to load commands, because Error: Could not read command file 'undefined'.

### ISSUE THREAD

**Issue by hanselke** [lukaspustina/hubot-bangbang#7]
bot started with:

env HUBOT_BANGBANG_COMMANDS="bangbang-commands.json" bin/hubot

reload bangbang commands requested by Shell.
[Tue Jan 10 2017 13:04:54 GMT+0800 (SGT)] ERROR hubot-bangbang: Failed to load commands, because Error: Could not read command file 'undefined'.
Shell: Reloaded. Now I recognize undefined command.

show bangbang commands requested by Shell.
Shell: Uh oh, I'm sorry. There no commands availabe right now. Try to reload the commands file.

env current gives me:
HUBOT_BANGBANG_COMMANDS_FILE=bangbang-commands.json
HUBOT_BANGBANG_TIMEOUT=10000
HUBOT_BANGBANG_LOG_LEVEL=info
HUBOT_BANGBANG_ROLE=bangbang
HUBOT_BANGBANG_SLACK=no

bangbang-commands.json is as per the example, and stored in the root directory of the app

[
  {
    "name": "date",
    "description": "retrieve local date from the specified host",
    "regex": "get date for (.+)",
    "exec": "echo ssh $1 date",
    "output_type": "plain"
  },
  {
    "name": "use report",
    "description": "retrieve an USE report from the specified host",
    "regex": "get use report for (.+)",
    "exec": "ssh $1 usereport.py",
    "output_type": "markdown",
    "timeout": 60,
    "role": "bangbang.use_report"
  }
]

**Comment by lukaspustina** [comment]
Hi,

can you try `env HUBOT_BANGBANG_COMMANDS_FILE="bangbang-commands.json" bin/hubot`?

**Comment by hanselke** [comment]
mm thanks. swear i tried that, but it works now. thanks!

On Tue, 10 Jan 2017 at 2:59 PM Lukas Pustina

<
mailto:Lukas Pustina <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hi,

can you try

env HUBOT_BANGBANG_COMMANDS_FILE="bangbang-commands.json" bin/hubot

?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/lukaspustina/hubot-bangbang/issues/7#issuecomment-271501140
, or

**Comment by lukaspustina** [comment]
Cool.
