### ISSUE TITLE
 Your command with ticket 'a4eedd1' finished with error code null, because of SIGTERM.

### ISSUE THREAD

**Issue by hanselke** [lukaspustina/hubot-bangbang#8]
is there anyway to deal with long running background tasks?

for instance when bangbang is used to install something

**Comment by lukaspustina** [comment]
Well, bangbang is not meant for such tasks. But you could try to increase the timeout which is 10 sec b default; cf. `HUBOT_BANGBANG_TIMEOUT`.

**Comment by lukaspustina** [comment]
@hanselke Does this help you? Can you close the issue in that case?
