### ISSUE TITLE
passing in commands with "" in exec:

### ISSUE THREAD

**Issue by hanselke** [lukaspustina/hubot-bangbang#9]
i'm trying to pass in 

  grep "dovecot" /var/log/maillog |grep "Aborted login" |cut -d "," -f 3 |cut -d ":" -f 4 |sort -n |uniq -c

in exec:

error i get is 

  ERROR hubot-bangbang: Failed to load commands, because Error: Could not parse command file 'bangbang-commands.json'

How do i pass in multiline and "" into exec?

**Comment by lukaspustina** [comment]
Can you show your commands.json file?
Why is this command chain multiline?

**Comment by hanselke** [comment]
so the standard command.json works, what im trying to add is..

 {

    "name": "locate incoming mail spam by subject",

    "description": "locate incoming mail spam by subject",

    "regex": "locate incoming mail spam by subject",

    "exec": "awk -F"T=\"" '/<=/ {print $2}' /var/log/exim_mainlog | cut -d\" -f1 | sort | uniq -c | sort -n",

    "output_type": "plain"

  },

  {

    "name": "locate email spam scripts sending into mail server",

    "description": "locate email spam scripts sending into mail server",

    "regex": "locate email spam scripts sending into mail server",

    "exec": "grep cwd /var/log/exim_mainlog | grep -v /var/spool | awk -F"cwd=" '{print $2}' | awk '{print $1}' | sort | uniq -c | sort -n",

    "output_type": "plain"

  },

  {

    "name": "see mail bruteforce attempts",

    "description": "see mail bruteforce attempts",

    "regex": "see mail bruteforce attempts",

    "exec": grep "dovecot" /var/log/maillog |grep "Aborted login" |cut -d "," -f 3 |cut -d ":" -f 4 |sort -n |uniq -c

    "output_type": "plain"

  }

I think the problem is that when i feed in the "" into the exec script, it gives an error.

I'm also hoping to have multiline, so that i can catch the return and parse it into a more human readable response

Hansel Ke

CEO

NextAction Pte Ltd

On Mon, 23 Jan 2017 at 11:29 PM Lukas Pustina

<
mailto:Lukas Pustina <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Can you show your commands.json file?

Why is this command chain multiline?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/lukaspustina/hubot-bangbang/issues/9#issuecomment-274518804
, or

**Comment by lukaspustina** [comment]
Escaping is the curse of IT. I'd propose to move the commands into individual shell script files and call these files from bangbang. In this way you can use all the power of a shell like multiline and parsing.

**Comment by hanselke** [comment]
do you have some sort of example i can follow? i can write my own bash scripts..

On Tue, 24 Jan 2017 at 2:26 AM Lukas Pustina

<
mailto:Lukas Pustina <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Escaping is the curse of IT. I'd propose to move the commands into individual shell script files and call these files from bangbang. In this way you can use all the power of a shell like multiline and parsing.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/lukaspustina/hubot-bangbang/issues/9#issuecomment-274573738
, or

**Comment by hanselke** [comment]
sorry, realized that was a pretty stupid question. 

what i meant was that some sort of pattern for me to store the bash scripts, and ideally a pattern to catch the responses and reply to chat?

On Tue, 24 Jan 2017 at 2:27 AM hansel@nextaction.co <
mailto:hansel@nextaction.co
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

do you have some sort of example i can follow? i can write my own bash scripts..

On Tue, 24 Jan 2017 at 2:26 AM Lukas Pustina

<
mailto:Lukas Pustina <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Escaping is the curse of IT. I'd propose to move the commands into individual shell script files and call these files from bangbang. In this way you can use all the power of a shell like multiline and parsing.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/lukaspustina/hubot-bangbang/issues/9#issuecomment-274573738
, or

**Comment by lukaspustina** [comment]
It's exactly the same as you already did before for other commands. Instead of calling the shell commands, you call the shell script instead. By calling I mean that you put the shell script into commands.json instead of the shell commands.

What ever your shell script outputs on stdout or stdin is passed as response to hubot.

**Comment by hanselke** [comment]
thanks. that worked
